### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by luyang-liu** [luyang-liu/SEBC#10]
* Deploy Coreset services
* create the direc in hdfs:
  hdfs dfs -mkdir /user/chen 
  hdfs dfs -mkdir /user/zhou

  sudo hdfs hdfs dfs -chown shanghai /user/chen
  sudo hdfs hdfs dfs -chgrp beijing /user/zhou
* Some commond:
  `hdfs dfs -ls /user`
 
  check the API version :
    http://ec2-54-202-229-53.us-west-2.compute.amazonaws.com:7180/api/versi/hosts
    http://ec2-54-202-229-53.us-west-2.compute.amazonaws.com:7180/api/version
    
* login HUE with hive name ,install the HIVE sample data

**Comment by mfernest** [comment]
Files not submitted for review.
