### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by luyang-liu** [luyang-liu/SEBC#6]
* Create user directories in HDFS for jimenez  and  beltran  
```
sudo -u hdfs hdfs dfs -mkdir /user/jimenez
sudo -u hdfs hdfs dfs -mkdir /user/beltran

```

* Login to Hue and install the Hive sample data

**Comment by mfernest** [comment]
See commit [9c9c426](https://github.com/luyang-liu/SEBC/commit/9c9c4264d8389fadb5167c852898fe0d5ceba661)
