### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by luyang-liu** [luyang-liu/SEBC#7]
* HDFS Testing
```
user root:
sudo -u hdfs hdfs dfs -chmod 777 /user/jimenez 
user :

time hadoop jar /opt/cloudera/parcels/CDH/jars/hadoop*-examples.jar teragen -Dmapred.map.tasks=8 -Ddfs.block.size=67108864 -Dyarn.nodemanager.resource.memory-mb=536870912 65536000  /user/jimenez/tgen


```

**Comment by mfernest** [comment]
Although your approach allows the user `jimenez` to write to HDFS, it also allows anyone else on the system to do the same . The correct approach is:
```
# sudo -u hdfs hdfs dfs -chown jimenez:rangers /user/jimenez
# sudo -u hdfs hdfs dfs -chmod 750 /user/jimenez
```
In this way, only the owner and group have write access to the location.

**Comment by mfernest** [comment]
See commit [63b8da4](https://github.com/luyang-liu/SEBC/commit/63b8da449f5b836d8210e90c18cf89f045c1dfa3)

The teragen command you used is not quite correct.
